Mtz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.Mantenimiento.urls', namespace='Mantenimiento', app_name='Mantenimiento'), name="Mantenimiento"),
]

admin.site.site_header = 'MasTec Mantenimiento R9 ATT'

modules/Mantenimiento/urls.py
from django.conf.urls import url
from .views import Index, Busqueda, Login, Detalle_Sitio, Preventivos, Preventivoform, Correctivos, Logout

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^(?P<error>[\w-]+)$', Index, name='index-disclaimer'),
    url(r'^$', Index, name='index'),
    url(r'^busqueda/$', Busqueda, name='busqueda'),
    url(r'^preventivos/$', Preventivos, name='preventivos'),
    url(r'^preventivoform/$', Preventivoform, name='preventivoform'),
    url(r'^correctivos/$', Correctivos, name='correctivos'),
    url(r'^login/$', Login, name='login'),
    url(r'^logout/$', Logout, name='logout'),
    url(r'^detallesitio/(?P<pk>\d+)/$', Detalle_Sitio, name='detalle_sitio'),
    #url(r'^region/(?P<region>[\w-]+)/$', lista_Sitiosxregion, name='sitios_por_region'),
    #url(r'^busqueda/$', Busqueda_Sitio, name='busqueda_sitio'),
    #url(r'^detallesitio/(?P<pk>\d+)/$', Detalle_Sitio, name='detalle_sitio'),
]

modules/Mantenimiento/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


'''
ToDo: OMAR

09-ENE-2018
Crear class tracker de correctivos

Crear class para control de llaves

13-MAR-2018
Agregar class FolioAttom para usar con class MOPs


'''

class Sitio(models.Model):
	site = models.CharField(max_length=80, null=False, blank=False)
	site_name = models.CharField(max_length=100, null=False, blank=False)
	iden = models.CharField(max_length=80, null=True, blank=True)
	gsm = models.CharField(max_length=100, null=True, blank=True)
	id_3g = models.CharField(max_length=100, null=True, blank=True)
	lte = models.CharField(max_length=100, null=True, blank=True)
	owner = models.CharField(max_length=100, null=True, blank=True)
	lat_decimal = models.DecimalField(max_digits=9, decimal_places=6, null=True)
	long_decimal = models.DecimalField(max_digits=9, decimal_places=6, null=True)
	site2 = models.CharField(max_length=80, null=True, blank=True)
	jerarquia = models.CharField(max_length=50, null=True, blank=True)
	jerarquia_modif = models.CharField(max_length=50, null=True, blank=True)
	co = models.CharField(max_length=100, null=True, blank=True)
	co_celular = models.CharField(max_length=100, null=True, blank=True)
	co_email = models.CharField(max_length=100, null=True, blank=True)
	coord = models.CharField(max_length=100, null=True, blank=True)
	coord_celular = models.CharField(max_length=50, null=True, blank=True)
	coord_email = models.CharField(max_length=100, null=True, blank=True)
	coord_mastec = models.CharField(max_length=100, null=True, blank=True)
	manager = models.CharField(max_length=100, null=True, blank=True)
	manager_celular = models.CharField(max_length=50, null=True, blank=True)
	manager_email = models.CharField(max_length=100, null=True, blank=True)
	director = models.CharField(max_length=100, null=True, blank=True)
	director_celular = models.CharField(max_length=50, null=True, blank=True)
	director_email = models.CharField(max_length=100, null=True, blank=True)
	coordination = models.CharField(max_length=50, null=True, blank=True)
	management = models.CharField(max_length=50, null=True, blank=True)
	region = models.CharField(max_length=20, null=True, blank=True)
	region_num = models.CharField(max_length=4, null=True, blank=True)
	mercado_ciudad = models.CharField(max_length=100, null=True, blank=True)
	mercado_anterior = models.CharField(max_length=100, null=True, blank=True)
	prioridad = models.CharField(max_length=4, null=True, blank=True)
	tipo_ante = models.CharField(max_length=50, null=True, blank=True)
	capacidad_gen = models.CharField(max_length=20, null=True, blank=True)
	cobertura_min = models.CharField(max_length=100, null=True, blank=True)
	acceso = models.TextField(null=True, blank=True)
	address = models.TextField(null=True, blank=True)
	municipality = models.CharField(max_length=100, null=True, blank=True)
	state_name = models.CharField(max_length=50, null=True, blank=True)
	nota_mastec = models.TextField(null=True, blank=True)
	fecha_modif = models.DateField(auto_now=True)
	fecha_creacion = models.DateField(auto_now_add=True)
	# Relación OneToOne tiene que ser unique
	capturado_por = models.ForeignKey(User, on_delete=models.CASCADE,)

	class Meta:
		verbose_name='sitio'
		verbose_name_plural='sitios'

	def __str__(self):
		return u"%s" % (self.site + " " + self.site_name)


class Contratista(models.Model):
	nombre_contratista = models.CharField(max_length=100, null=False, blank=False)
	razon_social = models.CharField(max_length=100, null=True, blank=True)
	contacto = models.CharField(max_length=100, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	telefono = models.CharField(max_length=50, null=True, blank=True)
	fecha_modif = models.DateField(auto_now=True)
	fecha_creacion = models.DateField(auto_now_add=True)
	capturado_por = models.ForeignKey(User, on_delete=models.CASCADE,)

	class Meta:
		verbose_name='contratista'
		verbose_name_plural='contratistas'

	def __str__(self):
		return u"%s" % (self.nombre_contratista)

MES = (
		('Enero','Enero'),
		('Febrero','Febrero'),
		('Marzo','Marzo'),
		('Abril','Abril'),
		('Mayo','Mayo'),
		('Junio','Junio'),
		('Julio','Julio'),
		('Agosto','Agosto'),
		('Septiembre','Septiembre'),
		('Octubre','Octubre'),
		('Noviembre','Noviembre'),
		('Diciembre','Diciembre'),
	)

'''
Tabla de programación de MOPs.
'''
class Mop(models.Model):
	site = models.ForeignKey(Sitio, on_delete=models.CASCADE,)
	owner = models.CharField(max_length=100, null=True, blank=True)
	site_type = models.CharField(max_length=100, null=True, blank=True)
	folio_attom = models.IntegerField(null=False, blank=False)
	tipo_mop = models.CharField(max_length=100, null=False, blank=False)
	mes_programado = models.CharField(choices=MES, max_length=50, null=False, blank=False)
	cantidad_mop = models.PositiveSmallIntegerField(null=False, blank=False)
	cantidad_mop_ejecutada = models.PositiveSmallIntegerField(null=False, blank=False, default=0)
	fecha_inicio = models.DateField(null=True, blank=True)
	fecha_fin = models.DateField(null=True, blank=True)
	semana_programada = models.PositiveSmallIntegerField(null=True, blank=True)
	eliminado = models.BooleanField(default=False)
	contratista = models.ForeignKey(Contratista, on_delete=models.CASCADE, null=True, blank=True)
	lider_contratista = models.CharField(max_length=100, null=True, blank=True)
	nota_mastec = models.TextField(null=True, blank=True)
	fecha_modif = models.DateField(auto_now=True)
	fecha_creacion = models.DateField(auto_now_add=True)
	capturado_por = models.ForeignKey(User, on_delete=models.CASCADE,)

	class Meta:
		verbose_name='mop'
		verbose_name_plural='mops'

	def __str__(self):
		return u"%s" % (self.tipo_mop)

class Moplog(models.Model):
	site_log = models.ForeignKey(Sitio, on_delete=models.CASCADE,)
	owner_log = models.CharField(max_length=100, null=True, blank=True)
	site_type_log = models.CharField(max_length=100, null=True, blank=True)
	folio_attom_log = models.IntegerField(null=False, blank=False)
	tipo_mop_log = models.CharField(max_length=100, null=False, blank=False)
	mes_programado_log = models.CharField(choices=MES, max_length=50, null=False, blank=False)
	cantidad_mop_log = models.PositiveSmallIntegerField(null=False, blank=False)
	cantidad_mop_ejecutada_log = models.PositiveSmallIntegerField(null=False, blank=False, default=0)
	fecha_inicio_log = models.DateField(null=True, blank=True)
	fecha_fin_log = models.DateField(null=True, blank=True)
	semana_programada_log = models.PositiveSmallIntegerField(null=True, blank=True)
	eliminado_log = models.BooleanField(default=False)
	contratista_log = models.ForeignKey(Contratista, on_delete=models.CASCADE, null=True, blank=True)
	lider_contratista_log = models.CharField(max_length=100, null=True, blank=True)
	nota_mastec_log = models.TextField(null=True, blank=True)
	fecha_modif_log = models.DateField(auto_now=True)
	fecha_creacion_log = models.DateField(auto_now_add=True)
	capturado_por_log = models.ForeignKey(User, on_delete=models.CASCADE,)

	class Meta:
		verbose_name='moplog'
		verbose_name_plural='moplogs'

	def __str__(self):
		return u"%s" % (self.tipo_mop_log)

modules/Mantenimiento/forms.py
from django import forms

class BusquedaForm(forms.Form):
	q = forms.CharField(label = "Sitio", widget=forms.TextInput(attrs={'placeholder': 'Buscar Sitio'}), max_length=80)

modules/Mantenimiento/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q
from .forms import BusquedaForm
from .models import Sitio, Mop


#from django.http import HttpResponse


'''
ToDo: OMAR

15-ABR-2018
Checar django-import-export para importar xls

Checar Django Axes para aumentar seguridad



'''




# Create your views here.

"""
Se requiere:
from django.contrib.auth import authenticate, login
"""
def Login(request):
	if request.method == 'POST':
		user = authenticate(username=request.POST['username'], password=request.POST['password'])

		if user is not None:
			login(request,user)
			return redirect('Mantenimiento:index')
		else:
			return HttpResponse("Error en usuario o contraseña")
	else:
		return render(request, 'Home/login.html')

def Logout(request):
	logout(request)
	return redirect('Mantenimiento:index')


def Index(request):

	if request.user.is_authenticated():
		form = BusquedaForm()
		return render(request, 'Mantenimiento/index.html',{'form': form, })
	else:
		return render(request, 'Mantenimiento/login.html',)
	#return render(request, 'Mantenimiento/index.html',)

	#return HttpResponse('Dentro de función Index')
	'''
	if request.user.is_authenticated():
		form = BusquedaForm()
		return render(request, 'Mantenimiento/index.html', {'form': form})
	else:
		return render(request, 'Mantenimiento/login.html',)
	'''

def Busqueda(request):

	if request.method == 'POST':
		form = BusquedaForm(request.POST)
		if form.is_valid():
			q = form.cleaned_data['q']

			sitios = Sitio.objects.filter(Q(site__unaccent__icontains=q)|
											Q(site_name__unaccent__icontains=q)|
											Q(iden__icontains=q)|
											Q(gsm__icontains=q)|
											Q(id_3g__icontains=q)|
											Q(lte__icontains=q)|
											Q(lte__icontains=q)

								)

			return render(request, 'Mantenimiento/index.html', {'sitios':sitios, 'form': form})

		else:
			elerror = True
			return redirect('Mantenimiento:index-disclaimer', elerror)
	else:
		form = BusquedaForm()
		return render(request, 'Disclaimer/index_disclaimer.html', {'form': form})
	pass



def Detalle_Sitio(request,pk):
	sitio = Sitio.objects.get(pk=pk)
	mops = sitio.mop_set.all()

	print("dentro Detalle_Sitio pk "+pk)
	#status = Status.objects.get(pk=pk)
	#mantenimiento = Mantenimiento.objects.get(pk=pk)

	print("sitio NAME: " + str(sitio.site_name))

	form = BusquedaForm()

	return render(request,'Mantenimiento/detallesitio_disclaimer.html', {'sitio': sitio,
																		'form': form,
																		'mops': mops,
																		}
					)


def Preventivos(request):
	form = BusquedaForm()
	return render(request, 'Mantenimiento/preventivos.html', {'form': form})



def Preventivoform(request):
	form = BusquedaForm()
	return render(request, 'Mantenimiento/preventivoform.html', {'form': form})


def Correctivos(request):
	form = BusquedaForm()
	return render(request, 'Mantenimiento/correctivos.html', {'form': form})

templates/Mantenimiento/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0052)http://getbootstrap.com/docs/4.0/examples/jumbotron/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'Mantenimiento/images/favicon.ico' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Archivo+Black" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Passion+One" rel="stylesheet">

    <title>MasTec México. Plantilla Mantenimiento desde Base.html</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'Mantenimiento/css/jumbotron.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
      <a class="navbar-brand" href="#">MasTec SGM</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Mantenimiento:index' %}">Inicio <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Preventivos</a>
          </li>
          <!--
          <li class="nav-item">
            <a class="nav-link disabled" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/#">Disabled</a>
          </li>
          -->

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'Mantenimiento:index' %}" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Correctivos</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Resumen</a>
              <a class="dropdown-item" href="#">Tickets abiertos</a>
              <a class="dropdown-item" href="#">Ticket cerrados</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <form method="post" action="{% url 'Mantenimiento:busqueda' %}" class="form-inline my-2 my-lg-0">
                {% csrf_token %}
                  {{ form.q }}
                  <button class="btn btn-success my-2 my-sm-0" type="submit">Buscar</button>
              </form>
            </a>
          </li>
        </ul>
        <strong class="text-white">Hola {{ user.first_name }}.</strong> <a class="nav-link" href="{% url 'Mantenimiento:logout' %}?next=/">Logout</a>  
              </div>
    </nav>



    {% block jumbotron %}
      <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
          <div class="container">
            <h1 class="display-3">MasTec México</h1>
            <p>Sistema de Administración de Información.</p>
          </div>
        </div>
    {% endblock  %}

  <!-- plantilla base.html -->
    {% block 'body' %}
    {% endblock  %}


    <footer class="footer navbar-fixed-bottom">
      <div class="container-fluid row-foot">
        <span class="text-muted">MasTec México.</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <!--
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    -->

      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug
    <script src="./bs_v4_02_files/ie10-viewport-bug-workaround.js.descarga"></script>-->

</body></html>

templates/Mantenimiento/correctivos.html
{% extends 'Mantenimiento/base.html' %}

    {% block jumbotron %}
    {% endblock  %}

    {% block 'body' %}
    <!-- plantilla index.html -->
            {% if elerror %}
              <div class="alert alert-danger" role="alert">
                <strong>Error: </strong> No existe Sitio con el criterio de búsqueda.
              </div>
            {% endif %}


          <div class="container contain-main py-1">
            <div class="row">
                <div class="col-12 col-md-12">
                    <div class="container bg-light py-3">

                      <h2 class="form-signin-heading">Buscar Sitio En Base Mantto.</h2>
                      <form method="post" action="{% url 'Mantenimiento:busqueda' %}">
                        <div class="form-row align-items-center">
                          <div class="col-auto">

                            <div class="input-group mb-2 mb-sm-0">
                              <div class="input-group-addon"><i class="material-icons md-18 md-white prefix">search</i>
                                </div>
                              {% csrf_token %}
                              {{ form.q }}
                            </div>
                          </div>
                          <div class="col-auto">

                          </div>
                          <div class="col-auto">
                            <button type="submit" class="btn btn-primary">Buscar</button>
                          </div>
                        </div>
                      </form>
                    </div>

                    <!-- Inicia container MAIN -->
                    <div class="container bg-light container-main">

                      <div class="row pt-1">

                        <div class="col-12">


                          <h2>CORRECTIVOS</h2>

                          <table class="table table-responsive table-bordered table-sm">
                              <thead class="bg-secondary">
                                <tr>
                                  <th scope="col">#</th>
                                  <th scope="col">ACTIVIDAD</th>
                                  <th scope="col">TIPO</th>
                                  <th scope="col">FECHA</th>
                                  <th scope="col">HORA REPORTE</th>
                                  <th scope="col">STATUS</th>
                                  <th scope="col">VALIDADO POR ATT</th>
                                  <th scope="col">NOTA</th>
                                </tr>
                              </thead>
                              <tbody>

                                      <tr>
                                        <th scope="row">1</th>
                                        <td>Suministro de diesel</td>
                                        <td>FLUIDOS</td>
                                        <td>20-ENE-2018</td>
                                        <td>16:00</td>
                                        <td><span class="badge badge-secondary">Realizada</span></td>
                                        <td><span class="badge badge-warning">Pendiente</span></td>
                                        <td>Pendiente Por: Arturo Cortés</td>
                                      </tr>
                                      <tr>
                                        <th scope="row">2</th>
                                        <td>Cambio De Jumper</td>
                                        <td>CORRECTIVO</td>
                                        <td>18-ENE-2018</td>
                                        <td>16:00</td>
                                        <td><span class="badge badge-success">Realizada</span></td>
                                        <td>Pendiente / Aprobado</td>
                                        <td>Pendiente Por: Arturo Cortés</td>
                                      </tr>
                                <tr>
                                  <td class="text-right">
                                    <button type="button" class="btn btn-primary">Agregar Ticket</button>
                                  </td>
                                </tr>
                              </tbody>
                            </table>


                        </div><!-- /col 12 -->

                      </div><!-- /row 1 -->




                    </div> <!-- Termina container MAIN -->



                </div>



                <!-- Inicia container menu derecha -->


            </div>
        </div>
    {% endblock  %}

templates/Mantenimiento/index.html
{% extends 'Mantenimiento/base.html' %}

    {% block jumbotron %}
    {% endblock  %}

    {% block 'body' %}
    <!-- plantilla index.html -->
            {% if elerror %}
              <div class="alert alert-danger" role="alert">
                <strong>Error: </strong> No existe Sitio con el criterio de búsqueda.
              </div>
            {% endif %}


          <div class="container contain-main py-1">
            <div class="row">
                <div class="col-12 col-md-12">
                    <div class="container bg-light py-3">

                        <div class="row pt-1">
                          <div class="col text-center">
                            <h1>Sistema De Gestión De Mantenimiento</h1>
                          </div>
                        </div>


                      <div class="row pt-1">
                        <div class="col-md-6 text-center">
                          <h2>MOPs</h2>
                          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                          <p>Información de Mantenimientos Preventivos Programados R9 AT&T. </p>
                          <p><a class="btn btn-info" href="{% url 'Mantenimiento:preventivos'%}" role="button">Resumen</a></p>
                        </div>
                        <div class="col-md-6 text-center">
                          <h2>Reparos Preventivos</h2>
                          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                          <p>Información de Mantenimientos Correctivos R9 AT&T </p>
                          <p><a class="btn btn-info" href="{% url 'Mantenimiento:correctivos'%}" role="button">Resumen</a></p>
                        </div>
                      </div><!-- /row -->


                    </div>

                    <!-- Inicia container MAIN -->
                    <div class="container container-main">

  
                        <div class="row bg-light">


                          {% if sitios %}
                            <div class="table-responsive"><!-- table-responsive -->
                                <table class="table table-striped ">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>IDATT</th>
                                      <th>SITE NAME</th>
                                      <th>IDEN</th>
                                      <th>GSM</th>
                                      <th>ID 3G</th>
                                      <th>LTE</th>
                                      <th>COORD ATT</th>
                                    </tr>
                                  </thead>
                                  <tbody>

                                    {% for sitio in sitios %}
                                      <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>
                                            {% if sitio.site %}
                                              <a href="{% url 'Mantenimiento:detalle_sitio' sitio.pk %}">
                                              {{sitio.site}}
                                              </a>
                                            {% else %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if sitio.site_name %}
                                              {{sitio.site_name}}
                                            {% else %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if sitio.iden %}
                                              {{sitio.iden}}
                                            {% else %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if sitio.gsm %}
                                              {{sitio.gsm}}
                                            {% else %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if sitio.id_3g %}
                                              {{sitio.id_3g}}
                                            {% else %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if sitio.lte %}
                                              {{sitio.lte}}
                                            {% else %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if sitio.coord %}
                                              {{sitio.coord}}
                                            {% else %}
                                            {% endif %}
                                        </td>
                                      </tr>
                                    {% endfor %}
                                  </tbody>
                               </table>
                            </div><!-- /table-responsive -->
                          {% endif %}

                        </div>


                    </div> <!-- Termina container MAIN -->



                </div>



                <!-- Inicia container menu derecha -->


            </div>
        </div>
    {% endblock  %}